name = "Pillow"
author = "Yannik Werner"
description = "A modern and minimal Hugo theme for blogs and portfolios with a collection of projects, recipes, books, a CV and blog entries."
version = "1.0.2"
license = "MIT"
homepage = "https://github.com/pillowbeast/hugo-pillow"
min_version = "0.88.0"
tags = ["personal", "blog", "portfolio", "minimal", "modern", "projects", "recipes", "books", "cv", "blog-entries"]
features = ["dark mode", "responsive design"]
exampleSite = "exampleSite"

